### ISSUE TITLE
vc-before-save and vc-after-save

### ISSUE THREAD

**Issue by conal** [jyp/dante#104]
I use git-emacs, which maintains a colored indicator in the mode line giving the git status of the file associated with the current buffer. This indicator is normally updated by `basic-save-buffer`, but dante uses `basic-save-buffer-1` instead. When flycheck is set to check on idle (as I like), the buffer gets saved without updating the colored git status indicator. A workaround is to surround the call to `basic-save-buffer-1` in `dante-async-load-current-buffer` as follows:

``` lisp
      (vc-before-save)
      (basic-save-buffer-1) ;; save without re-triggering flycheck/flymake nor any save hook
      (vc-after-save)
```

Perhaps there's a better solution.

**Comment by conal** [comment]
Any thoughts on this tweak? Would you be interested in a pull request?

**Comment by jyp** [comment]
There is a tension between calling save hooks and not calling them. Some people seem to want them, others not. (Using a temporary buffer has other problems, namely confusing GHCi to a large extent.) 

As a first measure, we can add exactly the hooks that you suggest, and see if it generates complaints. If this is still current, I'll be welcoming a pull request, thanks!

**Comment by conal** [comment]
Thanks!

**Comment by jyp** [comment]
Should be fixed by your PR. Closing.
