### ISSUE TITLE
[C-c ,] on operators

### ISSUE THREAD

**Issue by elgusy** [jyp/dante#106]
Is there some reason [C-c ,] does not work on operators?
This works well, however marking the operator and hitting [C-c ,] does not.
`
-- >>> :i (+)
-- class Num a where
--   (+) :: a -> a -> a
--   ...
--   	-- Defined in ‘GHC.Num’
-- infixl 6 +
`

**Comment by jyp** [comment]
The function `dante-ident-at-point` does not deal well with operators. Perhaps we can steal the logic from intero here.
