### ISSUE TITLE
`dante-repl-command` Errors when defined in dir locals

### ISSUE THREAD

**Issue by emilypi** [jyp/dante#109]
I updated Dante to the most recent version, and now the `.dir-locals.el` in all of my projects are generating some variation of the following error:

```
Error while checking syntax automatically: (file-missing "Searching for program" "No such file or directory" "<some command> <some dante-target here> <additional args here>")

```

It seems consistent among all the builds. When commented out, the target is picked up as usual and the `alist` functions work fine.

**Comment by jyp** [comment]
I have not experienced this. It's pretty hard to figure out what's going on with this message only. What is your .dir-locals.el file, etc?

I have updated the way dante is configured, please check the customization options again.

**Comment by emilypi** [comment]
Thanks for getting back @jyp! my `.dir-locals.el` is:

```
((nil . ((dante-target . "lib:pact")
         (dante-repl-command-line . (("nix-shell" "--run" (concat "cabal repl " (or dante-target "") " --builddir=dist/dante")))))))
```

I'll upgrade and see if it worked.

**Comment by jyp** [comment]
Upgrading seems the sensible option, I have done changes recently. Let me know.

**Comment by emilypi** [comment]
Works now 👍 thanks @jyp
