### ISSUE TITLE
Dante overwrites file when using magit-diff-visit-file

### ISSUE THREAD

**Issue by matthewbauer** [jyp/dante#110]
When using magit-diff-visit-file, you visit an old buffer that looks like this:

```
path/to/file.~my-branch~4~
```

Apparently dante tries to save this as the current file.

**Comment by jyp** [comment]
Alright. Dante needs to be disabled on such buffers (presumably they should not be edited). Would you propose a pull request?

**Comment by jyp** [comment]
Should be fixed by c7d7070
