### ISSUE TITLE
Disable autosave?

### ISSUE THREAD

**Issue by voanhduy1512** [jyp/dante#111]
Hi,

Recently I switch from intero to dante because of nix, i enjoy it so far but there is a issue that bother me is dante autosave the file every time i stop typing. I am not sure why that's the case. It makes company stop working and a few other unwanted things (flycheck and stuffs) appear.
How can i disable this feature in dante, i saw the readme and thought it's a opt-in feature but turn out it not. I haven't setup auto save or anything, and it only happens in dante mode

**Comment by emilypi** [comment]
Ditto. The constant writing and rewriting also causes unnecessarily many jobs to build up for GHCI, which means you have to wait 10-20 seconds on small projects and _minutes_ on larger projects (see: 50k-100k line projects) in order for the build queue to process.

**Comment by soupi** [comment]
The bottom of the [ readme in this repo](/soupi/minimal-haskell-emacs) explains the two alternatives i know of including that enables temp files.

**Comment by jyp** [comment]
@soupi gave the best possible answer. Unfortunately temporary files confuses GHCi (several files for the same module), so this is a "wontfix".
