### ISSUE TITLE
What does decide to use cabal new-repl?

### ISSUE THREAD

**Issue by aphorisme** [jyp/dante#124]
Hello! thanks a lot for dante.  : )

For now, I would like to change to `cabal new-repl` and all these nix-style commands. But dante keeps using `cabal repl` which reverts to a "missing dependency" error. What does decide that dante uses the `new-x` commands? And how can I set it to do so?

Edit: So, as far as I can see it is determined by a `cabal.project` file. Point was, that `cabal init` and then ` cabal new-configure` does not create such a file, but a `cabal.project.local`.

**Comment by jyp** [comment]
Do you think that the logic should be changed to test for `cabal.project.local`? Is `cabal.project` optional for new-style builds?

**Comment by aphorisme** [comment]
Hey, sorry for the late response. So, I would say it would be good to test for `cabal.project.local` as well, since a simple `cabal init` followed by `cabal v2-configure` leaves the directory with a `cabal.project.local` but not a `cabal.project`.

But this is not from the cabal spec, just by testing. So it is not official.
