### ISSUE TITLE
Company completion

### ISSUE THREAD

**Issue by ElvishJerricco** [jyp/dante#13]
It'd be nice to have company-mode autocompletion. I believe this is possible with GHCi, right?

**Comment by jyp** [comment]
In GHCi the completion is for the prompt only, AFAIU. Correct me if I'm wrong.

**Comment by ElvishJerricco** [comment]
I'm not sure. But I think `haskell-interactive-mode` is 100% based on GHCi, and it can provide completion.

**Comment by ljli** [comment]
GHCI has a command to query completions.
https://github.com/ghc/ghc/blob/master/ghc/GHCi/UI.hs#L281

**Comment by jyp** [comment]
According to [1]:

https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/ghci.html

**Comment by puffnfresh** [comment]
Can't we use the "repl domain" for this? I'm not really sure what a domain is, but I get useful identifier completions:

```
ghci> :complete repl "map"
4 4 ""
"map"
"mapM"
"mapM_"
"mappend"
```

It seems like this is what Intero uses.

**Comment by jyp** [comment]
Let's use the repl domain for now until GHCi can do something more clever.
