### ISSUE TITLE
Snack - file or directory doesn't exist

### ISSUE THREAD

**Issue by vanceism7** [jyp/dante#131]
Setup dante (for spacemacs) using the instructions listed here: https://www.fosskers.ca/blog/nix-en.html#org3819c30

Seems like dante installed ok, but when dante is invoked, it spits out this error in the `messages` buffer

```
Dante: Starting GHCi: snack ghci
Error while checking syntax automatically: (file-missing "Searching for program" "No such file or directory" "snack")
```

Glancing through the PRs, it looked like snack was just integrated into dante's setup. Is there something extra that needs to happen to get snack installed during dante's installation?

**Comment by vanceism7** [comment]
So, turns out (as the error said), you just need to install `snack` and this error goes away. I'll leave a link here for it: https://github.com/nmattia/snack

**Comment by timokratia** [comment]
Hi, apologies for digging out this closed issue. I just ran into the same problem (Emacs/macOS), and was able to solve it by deleting an older version of `dante` on the package-list-packages (it was listed as an dependency) and then reinstalling it. Thus it is not required to manually install `snack` using `nix`.

I haven't used the mac for nearly a year and was updating packages on my Emacs when running into this problem. Hope it might be helpful to those in a similar situation.
