### ISSUE TITLE
dante no longer supports v1 commands

### ISSUE THREAD

**Issue by Ptival** [jyp/dante#141]
Since cabal 3.0, `cabal repl` points to `cabal v2-repl` as opposed to `cabal v1-repl`.

The methods alist is thus obsolete, since it uses `cabal new-repl` and `cabal repl` which, currently, do the same thing, and in the future, may move again.

It seems the alist should be updated to use instead the more explicit `v1` and `v2` flags so as to solve the current issue and avoid such issues in the future.

**Comment by jyp** [comment]
Thanks!
