### ISSUE TITLE
`dante-type-at-time` doesn't show types in some cases

### ISSUE THREAD

**Issue by korayal** [jyp/dante#142]
I can't figure out the reason, but when I'm on a keyword and wait for the `dante-type-at-time` duration, I do not always get the type signature at the mini-buffer. The ones I'm getting are mostly trivial ones like `fmap`, `fromIntegral` etc.

But when I run `dante-type-at` on the same keyword, I can get the correct type. Does `dante-type-at-time` execute something other than `dante-type-at`?

**Comment by jyp** [comment]
This code was completely rewritten. Hopefully fixed the issue.
