### ISSUE TITLE
I wrote a blog post "How I use dante"

### ISSUE THREAD

**Issue by tomjaguarpaw** [jyp/dante#143]
This isn't really an issue, but something I wanted to bring to your attention. I've been really enjoying using dante recently so I wrote a blog post [How I use dante](http://h2.jaguarpaw.co.uk/posts/how-i-use-dante/) to help others.  I hope it will persuade more people to try dante and help them use it!

**Comment by jyp** [comment]
Thanks a lot. I've linked your post from the README.
