### ISSUE TITLE
Problem with global-flycheck-mode enabled

### ISSUE THREAD

**Issue by nosewings** [jyp/dante#153]
When Dante is used in combination with `(global-flycheck-mode)`, after viewing a Flycheck error by moving the cursor over the offending text, the `*Flycheck error messages*` buffer cannot be opened. In particular, trying to navigate into it with `C-x Left` or `C-x Right` simply does nothing, which can make buffer navigation somewhat more difficult.

**Comment by jyp** [comment]
I am not experiencing this issue, please provide a more extended description of what's happening, peshaps a screencast gif if you can. Also, this sounds like a flycheck issue, and I have just fixed the flymake backend so you may want to try that and see if you get a better experience.
