### ISSUE TITLE
use-package error

### ISSUE THREAD

**Issue by sboosali** [jyp/dante#16]
evaling

```
(use-package dante
    :ensure t
    :commands 'dante-mode
    :init
    (add-hook 'haskell-mode-hook 'dante-mode)
    (add-hook 'haskell-mode-hook 'flycheck-mode))
```
gives
```
package-compute-transaction: Package ‘dante-’ is unavailable
```
as does just
```
(use-package dante
    :ensure t
)
```

why is there a hyphen?  dante.el is on my load path too.

**Comment by sboosali** [comment]
(i'm new to use-package, btw)

**Comment by jyp** [comment]
I have no idea what's going on. You could try getting dante manually and adding a load-path argument to use-package.

**Comment by sboosali** [comment]
got it to work manually. might be an older version of use-package.
