### ISSUE TITLE
Setting up Dante Targets for enabling jump to definition and repl

### ISSUE THREAD

**Issue by abhaasgoyal** [jyp/dante#164]
Facing a similar problem as #147 with the [Dhall](https://github.com/dhall-lang/dhall-haskell) package 

After cloning it, I set `.dir-locals.el` to run the project through the haskell stack:

```
((nil . ((dante-methods . (stack)))))
```

After this `info-at-point` was working correctly, however neither running the repl nor jumping to defs were functioning (tried via `xref-find-defs` and `haskell-mode-jump-to-def-or-tag`). So I tried to set the dante targets for specific folders

```
((nil . ((dante-methods . (stack))))
 ("dhall-yaml" .
  ((nil . ((dante-target . "dhall-yaml:exe:dhall-to-yaml-ng")))))
                                        ; Some more folders here like dhall-json, dhall-text, etc
 ("dhall" .  ((nil . ((dante-target . "shall"))))))
```

But now even though the repl is working, other features such as info at point and jump to definitions are still not working... So how would one configure dante to work with this package

My haskell [config](https://github.com/abhaasgoyal/emacs.d/blob/master/lisp/init-haskell.el) (Config almost same as @purcell)

**Comment by jyp** [comment]
I've fixed the problem with multi-package jump to definition issue. The `info` feature has always been unreliable, but I'm blaming GHC on this one. This issue being stale anyway, I'm closing for now.
