### ISSUE TITLE
Possibility to use without `cabal-install`.

### ISSUE THREAD

**Issue by utdemir** [jyp/dante#17]
First, this is very useful, thanks for creating!

I switched my emacs configuration to use `dante`; because I do not want to depend either on `stack/intero` or `ghc-mod`. However, Dante still depends on `cabal-install` and which I do not generally install because I use `nix` instead. Is there a way to use only only `ghci` instead of `cabal-repl`? I'm ready to give up some more features if they require `cabal repl`.

But still depending on `cabal-install` is better than `ghc-mod` or `intero`; since it's easier to install and much more common.

**Comment by jyp** [comment]
Yes, you can use GHCi directly. You can configure `dante-repl-command-line-methods-alist` and even `dante-repl-command-line` for this purpose.

**Comment by soupi** [comment]
Hi!

what do i need to write in my `.emacs` file to use `stack repl` instead of `cabal repl`?

Thanks!

**Comment by jyp** [comment]
@soupi 
```
(setq dante-repl-command-line '("stack" "repl" dante-target))
```
will force using "stack repl".

**Comment by soupi** [comment]
Thanks!
