### ISSUE TITLE
Emacs 24.x support

### ISSUE THREAD

**Issue by JAremko** [jyp/dante#20]
Is there any chance that `dante` can support Emacs 24.x in the future?

**Comment by jyp** [comment]
I am not testing with emacs 24.x, so I am likely to fail at doing this properly. I'm accepting PRs though.

**Comment by hvr** [comment]
@jyp It may be worth mentioning which Emacs version is recommended/supported in the README; I've got no problem upgrading Emacs 25.x if I know it's needed/recommended upfront... :-)

**Comment by jyp** [comment]
The requirements of emacs packages are listed in a machine-readable format.
So you can see them when you install the package, and also on melpa:

https://stable.melpa.org/#/dante
