### ISSUE TITLE
Type inspection misreports, when symbols are used

### ISSUE THREAD

**Issue by Fresheyeball** [jyp/dante#23]
I have the following function

```
foo :: Int -> Int
foo x = x + 1
```

type inspecting works for either representation of `x` as we would expect.

```
foo :: Int -> Int
foo x = x + 1
 -- ^ C-c-. 
```

`x :: Int`

```
foo :: Int -> Int
foo x = x + 1
     -- ^ C-c-. 
```

`x :: Int`

But for this function, things are jacked

```
quadOut :: Fractional a => a -> a
quadOut time = negate time * (time - 2)
      -- ^ C-c-. 
```

`time :: a`

```
quadOut :: Fractional a => a -> a
quadOut time = negate time * (time - 2)
                    -- ^ C-c-. 
```

`interactive:1:1: error: Variable not in scope: time`

This is obviously wrong as the code compiles fine and `time` is clearly in scope.

```
quadOut :: Fractional a => a -> a
quadOut time = negate time * (time - 2)
                            -- ^ C-c-. 
```

`time :: a -> a -> a`

This is more evil as it's actually misleading. If I as an engineer did not already know the type of `time` and was looking to learn the type (the purpose of this feature), I would have no way of knowing the feedback being given is outright false.

## The symbol of doom

This bug goes away if `prettify-symbols` mode is turned off. In the function `quadOut`, the problem is caused by an interaction with:

```
(defconst prettify-symbols-alist
  '(...
    ("negate" . ?¬)
    ...))
```

Observed in spacemacs

**Comment by jyp** [comment]
I am not really understanding this issue.

Do you mean that prettify-simbols messes with the column numbers?

**Comment by jyp** [comment]
Closing due to lack of info.

**Comment by Fresheyeball** [comment]
Sorry I don't check these message often. Yes, the prettify-symbols messes with location info.

**Comment by jyp** [comment]
@Fresheyeball IMO this is a problem with prettify-symbols. It probably changes the behaviour of column-number querying.
