### ISSUE TITLE
Flycheck + hlint

### ISSUE THREAD

**Issue by pjones** [jyp/dante#3]
First off, I love dante.  It allowed me to strip a ton of workarounds out of my Emacs configuration.  Thank you!

The only thing I miss from my previous configuration is flycheck providing warnings from hlint.  I'm guessing something in haskell-mode was turning that on for me.  Any suggestions on how to enable that with dante?

Thank you.

**Comment by jyp** [comment]
Thanks for your kind words.

Actually I've never figured out how to run checkers in cascade with flycheck. You may want to check the function flycheck-add-next-checker.

**Comment by ElvishJerricco** [comment]
This works for me:

```elisp
(add-hook 'dante-mode-hook '(lambda () (flycheck-add-next-checker 'haskell-dante '(warning . haskell-hlint))))
```

**Comment by jyp** [comment]
Awesome, thanks @ElvishJerricco !

I've added this info in the README.

**Comment by pjones** [comment]
Awesome!
