### ISSUE TITLE
Can't find Stack's global ghc?

### ISSUE THREAD

**Issue by tsoernes** [jyp/dante#30]
Trying to start dante on a haskell file without a corresponding cabal or stack.yaml file I get this:
```
 Command line:(cabal repl)
 Loaded: 
 State: dead
 Queue: nil
 Callback: #[128 \302\300\303\301""\207 [dante-wait-for-prompt (mklinks.hs :set -Wall
:set +c
:set prompt "\4%s|" cabal: The program 'ghc' version >=6.4 is required but it could not be found.
 #[257 \301\302!\210\303\300!\207 [ dante:: /home/torstein/config/ message GHCi started! dante-schedule-next] 3 

(fn START-MESSAGES)]) apply append] 6 

(fn &rest ARGS2)]
```
I only have Stack installed on my system, so `stack ghc` is reachable and working through terminal but not `ghc`.

**Comment by thumphries** [comment]
If there is no `stack.yaml` file in the project, dante will [fail over](https://github.com/jyp/dante/blob/bf5d2bfc9a1696b97b1658a8090fdf80b6e9a730/dante.el#L125) to `cabal repl`.

You may wish to provide a custom command line to invoke `stack repl` at all times, or whatever it is you prefer.

It might look something like this:

```elisp
    (let
      ((methods `((stack  . ,(lambda (_) '("stack" "ghci" dante-target))))))
      (setq dante-repl-command-line-methods-alist methods))
```

... though maybe the defaults could be better, I don't know.

**Comment by tsoernes** [comment]
That seems to work. Haskell is nice for scripting in which case a `stack.yaml` file is unnecessary and unwanted. Thanks!
