### ISSUE TITLE
void `dante-command-line`, then hangs 

### ISSUE THREAD

**Issue by sboosali** [jyp/dante#33]
I get this error when loading 

`error in process sentinel: save-current-buffer: Symbol’s value as variable is void: dante-command-line`
`error in process sentinel: Symbol’s value as variable is void: dante-command-line`

then Emacs hangs if I use any Dante functions (like type-of).

my initialization:

`
(use-package dante
   :commands 'dante-mode
   :init
   (add-hook 'haskell-mode-hook 'dante-mode)
   (add-hook 'haskell-mode-hook 'flycheck-mode))`

Dante version is the latest (as of today).

**Comment by jyp** [comment]
Fixed by 42b2ef4
