### ISSUE TITLE
Restarting Dante does not re-eval a nix expression

### ISSUE THREAD

**Issue by Fresheyeball** [jyp/dante#35]
If I edit a Haskell file that is in a dependency and restarts Dante from spacemacs, the ghci process restarts, but the nix expression does not re-evaluate. Meaning the new ghci process receives an out of date dependency. When in a nix context, either restarting Dante should re-eval the nix expression, or that option should be provided as another command `restart-dante-hard` or something.

**Comment by jyp** [comment]
I don't think that this bug report is accurate. Dante re-runs `nix-shell` if the nix method is active. Trace `dante-repl-command-line` to check what happens.
