### ISSUE TITLE
Feature Request: Auto complete for language pragmas

### ISSUE THREAD

**Issue by Fresheyeball** [jyp/dante#37]
Remembering how to spell language pragmas sucks. Ghc-mod has this so I know it's possible.

**Comment by jyp** [comment]
I mostly use auto-fix for this. 

Besides this PR provides some support already https://github.com/jyp/dante/pull/24
Could you check what is missing?

**Comment by jyp** [comment]
The best method is to use autofix: use the extension first then use autofix on the error.

**Comment by sellout** [comment]
@Fresheyeball structured-haskell-mode also does this (I think … at least, _some_ mode I’m using does) and should work fine with Dante.

**Comment by hvr** [comment]
Fwiw, if you `M-x package-install haskell-snippets`, you get autocompletion via https://github.com/haskell/haskell-snippets/blob/master/snippets/haskell-mode/lang-pragma

**Comment by Fresheyeball** [comment]
@sellout I'm using the `structured-haskell-mode` for this now. But I would rather have better separation of concerns. `structured-haskell-mode` does it through `stack` I'd like it to be independent.

**Comment by jyp** [comment]
The way that company mode is structured, you can add a completer which only completes pragmas. (This functionality has nothing to do with GHCi and thus I do not think that it belongs in dante.)

**Comment by bezirg** [comment]
I do have completion of LANGUAGE pragmas, when using the standard `haskell-mode` package combined with `company` auto-completion packagin. Just make sure that `company-capf` is part of the local variable `company-backends`:

```lisp
(add-hook 'dante-mode-hook
          (lambda ()
            (company-mode)
            (set (make-local-variable 'company-backends)
                 '(company-capf))))
```

**Comment by purcell** [comment]
> I do have completion of LANGUAGE pragmas, when using the standard `haskell-mode` package combined with `company` auto-completion package. Just make sure that `company-capf` is part of the local variable `company-backends`:

The issue I found with this is that `company-capf` and `dante-company` fight about who should get to complete a symbol. I submitted https://github.com/jyp/dante/pull/118 in order to have `dante-company` punt when asked to complete inside a comment, which allows the `haskell-mode` pragma completion to kick in with just the standard dante config.

**Comment by purcell** [comment]
The fix for this has been merged, so the issue can probably be closed if someone would like to confirm it works for them with the stock `company` configuration.

**Comment by jyp** [comment]
Yep, this works. Thanks @purcell.
