### ISSUE TITLE
Feature request: Insert import

### ISSUE THREAD

**Issue by Fresheyeball** [jyp/dante#39]
This is another thing ghc-mod has now I really wish was there in Dante. Basically, you can highlight a symbol, and ask to insert the import for that symbol. This would be a 2 stage interaction, as that symbol may be in more than one module, and the developer must choose.

**Comment by jyp** [comment]
You can usually type the symbol in an expression; then GHC will propose an import if applicable; then you can use autofix to add the import.

Please check if that suits your workflow.
