### ISSUE TITLE
Info buffer steals focus.

### ISSUE THREAD

**Issue by Fresheyeball** [jyp/dante#41]
When asking for info `C-c-,` the info shows up in a new buffer (unlike asking for a type). This buffer steals focus from the existing buffer making subsequent commands not work without reverting focus. The behavior of info should be more in line with the behavior of getting the type.

**Comment by jyp** [comment]
dante uses `with-help-window` to open the info window. You can customize the focus-stealing behaviour using `help-window-select`.
