### ISSUE TITLE
Dante with Docker dev container?

### ISSUE THREAD

**Issue by dabro** [jyp/dante#44]
How would you recommend using Dante running in a host Emacs on a client docker container?  Unfortunately, a lot of the below seems to deal more with haskell-mode than dante.

1. GHCi and cabal in the container, 
2. volumes accessible on host, mounted in container.

Naive approaches have not worked.  
1.  I had partial success with editing `dante-repl-command-line` to attach to a running container, or call `docker exec`.  This required mounting my `/var` (actually `/private/var/folders` Mac OS?) so the container ghci could see all the temp files dante loads.  This allows type/info checks only.  BTW, why does Dante load temp files, vs the underlying file?
2.  I updated `haskell-process-path-cabal` from the underlying haskell-mode to do the same.  This allowed `haskell-compile` to run, but not `haskell-process-cabal-build` or any of the other cabal commands from `haskell-process-cabal`.  This seems to be because `haskell-load.el:245` directly constructs a local command: `(shell-command (concat "cabal " command)`, if there isn't an interactive haskell process running.  
3. I haven't unraveled why changing `haskell-process-path-cabal` to forward through `docker exec`, like `dante-repl` and and `haskell-comple`, simply causes the haskell-session to crash repeatedly...
4. Using docker-tramp to establish a remote environment to the container chokes on cabal `/bin/sh: 1: cabal: not found`.  I'm pretty sure this is because my profile is being overridden.
```
(tramp-own-remote-path "/bin" "/usr/bin" "/sbin" "/usr/sbin" "/usr/local/bin" "/usr/local/sbin" "/local/bin" "/local/freeware/bin" "/local/gnu/bin" "/usr/freeware/bin" "/usr/pkg/bin" "/usr/contrib/bin" "/opt/bin" "/opt/sbin" "/opt/local/bin")
```
While `tramp-own-remote-path` is supposed to inject profile settings, there are warnings on the tramp site that `bin/sh` can't process `~` or `export PAR=ARG` syntax.

Overall, however, I think tramp is likely sub-optimal -- I'm compressing and transferring a file from the container to the host, which docker mounted in the container from the host to begin with.  It maybe possible to just get the remote shell aspect by editing `default-directory` to one that Emacs recognizes as remote, but I'm not sure of the implications there when actually loading files locally on host.

**Comment by jyp** [comment]
> This allows type/info checks only

Weird; all functionality goes through a single GHCi instance so if type/info works everything should be fine.

>  why does Dante load temp files, vs the underlying file?

Because flycheck works on the buffer contents, not the saved file. Dante follows the same convention to minimize surprises.

**Comment by jyp** [comment]
Dante supports (ssh) tramp files now, without any special configuration.
