### ISSUE TITLE
Wrong stanza's dependencies loaded

### ISSUE THREAD

**Issue by Rotaerk** [jyp/dante#45]
I have a cabal file containing a library stanza followed by an executable stanza.  I have run emacs from the directory containing the cabal file, and I have opened a source file from the executable (i.e. the second) stanza.  Dante highlights some of the imports in that source file, indicating a failure to load the interface, and suggesting that I add the package is comes from to my cabal file.  The imports for which this is an issue are the ones that exist in the executable stanza's build-depends but not in the library stanza's build-depends.

This is the same behavior that I see if I run 'cabal repl'.  In this case, the solution is to run 'cabal repl exename', which tells it to load the dependencies of that particular stanza.  I don't know what the solution is in the case of dante.

**Comment by Rotaerk** [comment]
Actually, I now see that's specifiable by setting the dante-target variable to the name of the stanza.  However, that's not quite ideal, because I wouldn't want to have to set that every time I switch from working on the source files for one stanza and the source files for another.

**Comment by Rotaerk** [comment]
I just learned about directory local variables.  I think this resolves the issue of having that setting specified per stanza.  Might be worth adding to the readme, though.

**Comment by knupfer** [comment]
I don't think that directory local variables is a good fix, because this would result in boilerplate for each project.

Note that this problem also occurs for test suites and benchmarks.
This complicates the issue because it would need a `cabal configure --enable-foo` beforehand.

Just bumped into this an hour ago...

**Comment by Rotaerk** [comment]
If we want to avoid the boilerplate entirely, it should be possible to identify which stanza a particular source file belongs to, based on its path and the paths specified in the cabal file.  It would require reading the cabal file, though.  Alternatively, cabal repl itself might be a better place for such a feature, i.e. load the component to which this source file belongs.  I noticed that 'cabal repl --help' indicates:  Support for loading specific modules is planned but not implemented yet.

**Comment by jyp** [comment]
Thanks @Rotaerk for finding what I consider the best course of action. :)
