### ISSUE TITLE
Maintaining state between `dante-eval-block` uses; multi-line evaluations?

### ISSUE THREAD

**Issue by dabro** [jyp/dante#46]
It's not clear to me how this feature is supposed to work:
```
{-> :set +t


-}
{-> let a = 1

a :: Num a => a
-}  
{-> a


<interactive>:94:1: Not in scope: ‘a’
-}
```
For clarity, I'm running quite a mongrel session; let me know if any of the behavior listed is contrary to your experience, and I'll troubleshoot my environment.  (For reference if needed:  cabal 1.22 project, spacemacs on OSX, build environment in docker haskell container running GHC 7.10.1.  My command to get this running is: `(dante-repl-command-line . ("sudo" "-E" "-u" "auser" "-s" "bash" "-i"  "-c"  "cd projroot && cabal repl --ghc-options='-ferror-spans'"))`, which is setup by a `.dir-locals.el` file in the repo I'm working on.)  

1.  Is this lack of state supposed to happen, or particular to my configuration?
2.  Is there any way to run multiple lines?
3.  Is there any integration with `haskell-interactive-bring` from `haskell.el`?  These seem to be two completely different sessions in my config.
4.  Is there someway to bring up the dante repl session to watch what's happening?  `dante-list-buffers` doesn't show it -- should it?
5.  How can one bring in other context or imports for testing and troubleshooting?  eg:
```
{-> :add *Main ...}
{-> :show modules

Service.Module.Types ( /var/folders/px/h7c3bvhd5j78hk34lsjc1gjc0000gp/T/danteKZSsC5.hs, interpreted )
Service.Module.Error.Types ( src/Service/Module/Error/Types.hs, dist/build/schmods-api/schmods-api-tmp/Service/Module/Error/Types.o )
-}

-- all the modules have disappeared from context
```
the use of temporary files causes ambiguities which cause some context changes to fail
```
{-> :add *Service.Module *Service.Module.Types *Project.Operations.Module *Project.Data.Module.Conversions *Project.REPL *Data.Time.Helpers


<no location info>:
    module ‘main@main:Service.Module.Types’ is defined in multiple files: /var/folders/px/h7c3bvhd5j78hk34lsjc1gjc0000gp/T/danteKZSsC5.hs
                                                                          /var/folders/px/h7c3bvhd5j78hk34lsjc1gjc0000gp/T/danteKZSsC5.hs
Failed, modules loaded: Service.Module.Types, Service.Module.Error.Types.
-}
```
Am I just misusing this feature?  Here's the scenario: I'm attempting to modify data types and Aeson serialization incrementally.  Any change to the types breaks a lot of helper functions, preventing the file from loading.  I'd like to test just the data type and `fromJSON` instances I'm changing, then go edit the helper functions, piece by piece by piece.

**Comment by jyp** [comment]
Firstly, GHCi is somewhat buggy and is not always in the state that you'd expect.

Second, dante does not feature a way to interact incrementally with a session (that's what ghci mode would be for).

However, I'm quite positive to the idea of a multi-line stanza. I'm guessing that intero has this feature, maybe I can steal its syntax.

**Comment by jyp** [comment]
Actually the syntax to use is documented here:

https://www.haskell.org/haddock/doc/html/ch03s08.html#idm140354810780208

**Comment by jyp** [comment]
So, to answer your questions clearly:

1. There is no support for state.
2. Starting from https://github.com/jyp/dante/commit/2505b021f048bb3445ec5779999f1ea4219ed7d7 yes
3. No
4. You can use configure dante-debug to see what is going on under the hood.
5. This may work with the above commit. But it is not officially supported (it may mess with flychecking). If you need other modules: import them.

**Comment by dabro** [comment]
I added some comments on the commit.

Really nice.  Thanks! I also saw this links into https://github.com/jyp/dante/issues/15 <https://github.com/jyp/dante/issues/15>. Are you still thinking about sessions, maintaining state, etc?  Also, when you load a source file into the base Haskell-mode repl, the type of a token under point is displayed in the mini-buffer.  This only seems to happen if I manually call info with Dante.  Not a big deal, but should I register an issue?

**Comment by jyp** [comment]
> Really nice.  Thanks! I also saw this links into #15. Are you still thinking about sessions, maintaining state, etc?

Let's move this discussion there.

> Also, when you load a source file into the base Haskell-mode repl, the type of a token under point is displayed in the mini-buffer.  This only seems to happen if I manually call info with Dante.  Not a big deal, but should I register an issue?

This would be called 'eldoc mode' support. You may file an issue, but I can't promise that I'll get to it soon. One reason is that it would clash with the existing haskell mode eldoc support.
