### ISSUE TITLE
Company completion breaks flycheck

### ISSUE THREAD

**Issue by purcell** [jyp/dante#48]
Steps to reproduce:

- Enable dante-mode, company-mode and flycheck in a .hs buffer
- Start typing on a blank line, with regular pauses, such that both `flycheck` and `company` are being triggered in quick succession, e.g. `dfa f  kjklj   adf a sdf asdf  sd f dfasd fdfsdfs  sdfasfdadfffd jlasdfjl`. Sometimes it's necessary to do this for a while until the "actual result" below is obtained.

Expected result:

- Flycheck continues to update the in-buffer errors

Actual result:

- Flycheck stops working, even after typing has finished.
- Flycheck appears to be in the "running" state.
- `dante-restart` must be called to restore functionality.

My guess is that some constellation of overlapping requests and conditions causes the flycheck checker's callback to not be called, leaving the check stuck. With `company` disabled, this does not happen.

(My `company-minimum-prefix-length` is 3, and flycheck triggers lazily, ie. is not set to only trigger on save/newline.)

------

Background: I'm one of the intero contributors, but I'm keen to adopt a solution with fewer moving parts, so I've been trying out dante in the last couple of days. This is really the only blocker for me.

I was playing with the `dante` code a little, and will file a separate issue with a suggestion that might be helpful to you.

Thanks!

**Comment by jyp** [comment]
What versions were you using? I've make a fix to the scheduling in 202ae44286d3640bd68116ce20a7fcb498618087

**Comment by purcell** [comment]
> What versions were you using?

It would have been the `master` version at the time of writing. I'll take a look at the new version. :-)

**Comment by purcell** [comment]
I checked with the latest version and the situation is unchanged. Seems worse, in fact: the moment I start to type, `flycheck` breaks, with the tell-tale `FlyC*` modeline marker indicating that `flycheck` believes there's a check in progress, which never finishes. And I never see any completions.

This happens with local projects using both a recent Stack LTS (so GHC 8.0.2) and Nightly (8.2.1). And this is in a very recent Emacs version, with the latest versions of Company and Flycheck.

**Comment by jyp** [comment]
Thanks a lot for bringing this issue to my attention. I have fixed a couple of issues and now I cannot reproduce the reported bug with HEAD. Could you please give it another try?

**Comment by purcell** [comment]
Great! Well, now the Flycheck is rock-solid, but the completions never return a result. The moment I type something, `flycheck` triggers and marks the inevitable errors in the buffer, but the thing I'm typing doesn't produce the expected `company` completions. I wonder if the act of loading the suddenly-invalid buffer means that the subsequent `:complete` fails?

A simple test I've tried is typing `inter` in a buffer which has `import Data.List (intercalate)`: in my case I see the option `interact` (from `Prelude`), but not `intercalate`.

**Comment by jyp** [comment]
@purcell Yep that's the expected behaviour. The moment that your code doesn't type check any longer, GHCi is unable to provide completions of symbols defined in the current module (only Prelude and module imports remain)

An improvement (but we should discuss this in another thread) would be to activate type errors as warnings.

**Comment by ElvishJerricco** [comment]
@jyp well it sounds like @purcell is saying it’s not even able to complete `intercalate`, which is an imported identifier. That ought to be possible, no?

**Comment by jyp** [comment]
@ElvishJerricco No; sorry if I was not clear. If there is an error, then only 'Prelude' is loaded. GHCi can then complete stuff from Prelude or module names.

**Comment by ElvishJerricco** [comment]
Oh I see. Well that seems like a bit of a deal breaker then, right? Basically means you have to choose between flycheck and company. How does Intero handle this?

**Comment by jyp** [comment]
> An improvement (but we should discuss this in another thread) would be to activate type errors as warnings.
