### ISSUE TITLE
Suggestion: use "tq" to manage process communication

### ISSUE THREAD

**Issue by purcell** [jyp/dante#49]
I don't know if you've seen the `tq` library built into Emacs. It's precisely for sending queued messages off to a backend process, waiting for a regexp match, and then returning that match to a callback. I love that you're keeping `dante` as simple and minimal as possible, and I feel like `tq` could be used to further simplify `dante` significantly. I played a little locally, and ended up with a version of `dante-async-call` which looks a little like the following:

```el
(defun dante-async-call (cmd cont)
  "Send GHCi the command string CMD.
The result is passed to CONT as (CONT REPLY).  Can only be called
from a valid session."
  (when (memq 'outputs dante-debug) (message "[Dante] -> %s" cmd))
  (let ((prompt-re "\4\\(.*\\)|"))
    (with-current-buffer (dante-buffer-p)
      (tq-enqueue
       dante-tq
       (concat cmd "\n")
       (concat "\\(.*?\\)" prompt-re)
       nil
       (lambda (_ response)
         (let ((reply (car (s-split-up-to prompt-re response 1))))
           (when (memq 'responses dante-debug)
             (message "[GHCi] <- %S" reply))
           (funcall cont cont reply)))
       t))))
```

There, `dante-tq` is the result of calling `tq-create` on the repl process, as in the following hacked version of `dante-start-process-in-buffer`:

```el
(defun dante-start-process-in-buffer (buffer source-buffer)
  "Start a Dante worker in BUFFER for SOURCE-BUFFER."
  (if (eq (buffer-local-value 'dante-state buffer) 'dead)
      buffer
    (let* ((args (-non-nil (-map #'eval (dante-repl-command-line))))
           (process (with-current-buffer buffer
                      (when (memq 'command-line dante-debug)
                        (message "GHCi command line: %s" (combine-and-quote-strings args)))
                      (message "Dante: Starting GHCi ...")
                      (apply #'start-file-process "dante" buffer args))))
      (set-process-query-on-exit-flag process nil)
      (with-current-buffer buffer
        (message "Setting transaction queue in %S" buffer)
        (setq-local dante-tq (tq-create process))
        (erase-buffer)
        (setq-local dante-command-line (process-command process)))
      (with-current-buffer source-buffer
        (set-dante-state 'starting)
        (dante-async-call
         (concat ":set -Wall\n"               ;; TODO: configure
                 ":set +c\n" ;; collect type info
                 ":set prompt \"\\4%s|\"")
         (lambda (cont reply) (message "GHCi started!"))))
      (set-process-sentinel process 'dante-sentinel)
      buffer)))
```

This is sufficient to get the message `GHCi started`, but my tinkering stalled when trying to get my head around the CPS stuff: I'm not sure whether or not that could be eliminated.

**Comment by jyp** [comment]
Thanks for the pointer! I'll look at this soon.

**Comment by jyp** [comment]
Unfortunately, even just a quick look shows that this is not usable. Indeed, afaics, despite the name, `tq` cannot manage transactions, in the sense of a series of unbreakable sequences of command/requests. This is quite important as dante often does `:load` and follow with another command. Actual transactions are important because flycheck runs loads in the background at unpredictable times.

**Comment by purcell** [comment]
Ah, that makes sense: while you could use `tq` to serialise requests to the back end, I guess you mean "transactions" in the sense of groups of related requests, e.g. `:set` then `:load` etc.

**Comment by jyp** [comment]
Exactly.
