### ISSUE TITLE
can projectile-kill-buffers kill Dante sessions too?

### ISSUE THREAD

**Issue by shajra** [jyp/dante#5]
Both Projectile and Dante are really nice, and for the most part, they work nicely together.

I also use emacs in daemon mode to save on startup time.  So buffers can sometimes accumulate, and I use `projectile-kill-buffers` to clean things up.  However, I just noticed that the associated Dante process buffers are staying alive.

My Elisp isn't so strong, but looked at `dante-destroy`.  It works fine when called manually, but a single projectile session can have multiple Dante process buffers (because of multi-project builds).

So for now, I'm using `dante-list-buffers` and killing the buffers interactively from there.

These background processes aren't really that big a deal.  They haven't bee consuming that many resources just idling in the background.  But I thought it would be nice to have a way to clean them up better.  Otherwise, Dante has integrated into my workflow super nicely (thanks for that).

**Comment by tmcgilchrist** [comment]
I've noticed this issue too, haven't had a chance to look into it.

**Comment by jyp** [comment]
Thanks. I'm not a projectile user so I have a hard time answering your question. If you find the appropriate projectile hook I can see if I can add dante there.

**Comment by tmcgilchrist** [comment]
It seems like the best way would be to work out how projectile tracks which buffers are associated with a project see `projectile-project-buffers`. It seems like it skips over buffers that aren't backed by a file but my lisp is not fantastic so I could be wrong. 

```lisp
(defcustom projectile-buffers-filter-function nil
  "A function used to filter the buffers in `projectile-project-buffers'.

(defun projectile-project-buffers ()
  "Get a list of project buffers."
  (let* ((project-root (projectile-project-root))
         (all-buffers (cl-remove-if-not
                       (lambda (buffer)
                         (projectile-project-buffer-p buffer project-root))
                       (buffer-list))))
    (if projectile-buffers-filter-function
        (funcall projectile-buffers-filter-function all-buffers)
      all-buffers)))

(defun projectile-project-buffer-p (buffer project-root)
  "Check if BUFFER is under PROJECT-ROOT."
  (with-current-buffer buffer
    (and (not (string-prefix-p " " (buffer-name buffer)))
         (not (projectile-ignored-buffer-p buffer))
         (string-equal (file-remote-p default-directory)
                       (file-remote-p project-root))
         (not (string-match-p "^http\\(s\\)?://" default-directory))
         (string-prefix-p project-root (file-truename default-directory) (eq system-type 'windows-nt)))))

```
