### ISSUE TITLE
Feature request: add eldoc for type (for thing at point)

### ISSUE THREAD

**Issue by marklar** [jyp/dante#51]
I realize that it seems minor, but it's astonishingly valuable to have the extra convenience of seeing the type displayed in the message area without having to request it (via `C-c .`).

**Comment by sboosali** [comment]
I'll take a look at this soon, doesn't seem hard

"ElDoc How to implement support": 
https://www.emacswiki.org/emacs/ElDoc#toc3

**Comment by michalrus** [comment]
+1! This would be very nice to have (switchable)!

**Comment by jyp** [comment]
Actually eldoc is a pretty bad choice for dante. This is because the GHCi call is asynchronous (and can take a long time to return a value), while the eldoc callback is synchronous. I am close to have a suitable alternative implemented (search for dante-timer in the code).

**Comment by sboosali** [comment]
isn't dante-type-at pretty fast, given ghci's `:all-types`? I guess that
assumes the buffer type-checks and hasn't been modified.

**Comment by jyp** [comment]
Right. It's often fast but can take a noticeable amount of time, eg. when a big file needs to be reloaded.

**Comment by jyp** [comment]
Done. Customize dante-tap-type-time to activate.
