### ISSUE TITLE
Completion works for the current module only if it can be loaded.

### ISSUE THREAD

**Issue by jyp** [jyp/dante#54]
The completions (almost) never return a result. The moment one types something, there are inevitable errors in the buffer, and GHCi won't load it. Thus it won't produce the expected company completions; only those from Prelude.

(I am paraphrasing @purcell above)

A possible (partial) workaround is to add `-fdefer-type-errors` to `dante-load-flags`. This way even work if the code won't typecheck GHCi will load the buffer. However, one will be bitten by #52

**Comment by purcell** [comment]
There are also issues with `-fdefer-type-errors`, IMO: see https://github.com/commercialhaskell/intero/pull/495#issuecomment-348867616.

**Comment by krgn** [comment]
I noticed that, when trying out intero yesterday, I had the same problems with it _until_ I cleaned my `nix` environment and had `stack` install all dependencies local to the project. Then completion suddenly worked. Not sure if that helps.

**Comment by doofin** [comment]
add `-fdefer-type-errors` also do not work for ghc 8.4,only symbols from prelude can be completed

**Comment by jyp** [comment]
I've committed a fix: the imports are loaded explicitly when trying to do a completion 0054272
