### ISSUE TITLE
Default `-Wall` overrides cabal settings 

### ISSUE THREAD

**Issue by guibou** [jyp/dante#55]
The default setting of `-Wall` in `dante-load-flags` overrides cabal settings if cabal contains some disabled warnings, for example `-Wno-missing-signature`.

This is not an important issue, but it can be surprising.

**Comment by jyp** [comment]
I don't mind removing `-Wall` from this list. But it deserves a special mention in the documentation I think. PR welcome.

**Comment by jyp** [comment]
Fixed as suggested.
