### ISSUE TITLE
Support for GHC 8.2 caret in error message

### ISSUE THREAD

**Issue by guibou** [jyp/dante#56]
GHC 8.2 introduces caret in error message, for example:

```
Err.hs:1:1: warning: [-Wmissing-signatures]
    Top-level binding with no type signature: f :: Num a => a -> a -> a
  |
1 | f x y = x + y
  | ^
```

Unfortunately, the `auto-fix` command is sometimes broken due to this caret. It can be disabled with `-fno-diagnostics-show-caret`. This is not a critical bug because this flag can be put in the init.el, however it can be surprising.

**Comment by jyp** [comment]
Thanks for this report!
