### ISSUE TITLE
Dante and cabal repl reset each other's incremental build state

### ISSUE THREAD

**Issue by themoritz** [jyp/dante#59]
Whenever dante checks a file in my emacs, and I subsequently run `cabal build` or `cabal repl` from the command line, it starts rebuilding _every_ module in my project. The same happens if after `cabal build`/`cabal repl` I start dante.

It would be great if dante and my commands could share the incremental build state.

I'm using nix, so both dante and `cabal build` are run inside nix-shell.

**Comment by michalrus** [comment]
If this is really the case (why would it be?), we could call Cabal with `--build-dir=dist-dante` to separate the two `dist`s.

See https://www.haskell.org/cabal/users-guide/installing-packages.html#cmdoption-setup-test-builddir .

But lemme verify on a big project of mine.

**Comment by michalrus** [comment]
E.g. in `$project/test/.dir-locals.el`:

```elisp
((nil . ((dante-target . "test:integration")
         (dante-repl-command-line . ("nix-shell" "--run" "exec cabal --builddir=dist/dante repl test:integration")))))
```

**Comment by themoritz** [comment]
Thanks @michalrus this simple idea already solves the biggest pain (resetting the incremental build state) for me. Let me know if you can reproduce this issue.

**Comment by jyp** [comment]
I am guessing that the states cannot be shared due to different flags being set. Perhaps we should set the builddir by defaut?

**Comment by michalrus** [comment]
If they cannot be shared, then I would say yes! :heavy_plus_sign:  But perhaps inside the already existing `dist/`, so that people don’t have to adjust their `.gitignore`s.

**Comment by michalrus** [comment]
@themoritz, I could’ve reproduced it, yes!

**Comment by jyp** [comment]
Sounds good, I'll add the option `--builddir=dist/dante` to methods which I know support it.
