### ISSUE TITLE
Overzealous comment overwriting

### ISSUE THREAD

**Issue by fosskers** [jyp/dante#61]
If you write a Dante eval block above a legitimate comment and then evaluate it, the legit comment will be overwritten:

```haskell
-- >>> foo 5
-- | Best function
foo :: Int -> String
foo = show
```
becomes
```
-- >>> foo 5
-- "5"
foo :: Int -> String
foo = show
```
  whereas I expected:
```haskell
-- >>> foo 5
-- "5"
-- | Best function
foo :: Int -> String
foo = show
```

**Comment by jyp** [comment]
You should use a blank line to separate the eval block from the next comment.

**Comment by fosskers** [comment]
Ok thanks, I'll keep that in mind.
