### ISSUE TITLE
Multi-target projects — “depender” GHCi doesn’t get changes from dependency?

### ISSUE THREAD

**Issue by michalrus** [jyp/dante#62]
If, in a single `.cabal` file, I have, say:

* a `library`,
* and an `executable something`,
* and make this executable depend on that library,
* and start Dante in this executable’s context (`cabal repl exe:something` in a `nix-shell`),
* and change some Haskell sources in the `library`…

… I have to do `M-x dante-restart` to get the library changes visible in executable’s Dante.

Is this the expected behavior? :o

**Comment by michalrus** [comment]
Also: when I do `M-x dante-restart`, I have to close the buffer and reopen it, or flycheck’s wiggles won’t change.

**Comment by michalrus** [comment]
Similarly, when I add some deps to `.cabal` and `M-x dante-restart`. Then I need to kill and reopen that particular file again.

**Comment by jyp** [comment]
dante-restart does not re-run flycheck. Does that explain what you're seeing?

**Comment by michalrus** [comment]
It does — the flycheck part! Thanks. Maybe it could? E.g. check if flycheck is available, and run `(flycheck-buffer)`?

I did some more testing and:

When I do `M-x dante-restart` after changing code in deps, and it is indeed restarted, and then if I do `M-x flycheck-buffer`… the flycheck feedback is still wrong. I have to kill the buffer, open it once more, restart dante, kill it, open it once more, and only then it’s OK. :o

**Comment by michalrus** [comment]
This is just a simple Cabal/Nix project with `library` and `executable`, where this `executable` depends on the `library`.

**Comment by jyp** [comment]
If a checker dies then flycheck goes bonkers. You have to restart it too. If you want this functionality please add a specific ticket.

I am unsure about the original issue, it is fixed or not?

**Comment by jyp** [comment]
Closing in absence of information
