### ISSUE TITLE
Feature Request: Incremental echoing

### ISSUE THREAD

**Issue by fosskers** [jyp/dante#64]
Dante seems to capture all of an `IO` function's output before echoing any of it back to the buffer. So given:

```haskell
import Control.Concurrent (threadDelay)

foo :: IO ()
foo = do
  putStrLn "Hi there!"
  threadDelay 1000000
  putStrLn "Okay bye"
```
Evaluating a `-- >>> foo` prints both messages back at the same time, which is different from the experience offered by a vanilla repl. Would it be difficult to echo each message back as soon as it appeared in STDOUT?

**Comment by jyp** [comment]
This would be difficult, not to mention confusing (there is no obvious prompt indicating that the evaluation is complete)

**Comment by fosskers** [comment]
Why not just echo chars as they appear in stdout?

**Comment by jyp** [comment]
Check the definition of dante-async-call and dante-wait-for-prompt.
