### ISSUE TITLE
lcr not automatically installed when installing from melpa

### ISSUE THREAD

**Issue by endgame** [jyp/dante#69]
Not sure if this is better filed here or with melpa; how are dependencies inferred?

If I try to `(use-package dante :ensure t)` without first installing `lcr`, it fails the `(require 'lcr)`.

I'm currently just working around it with:

```elisp
(use-package lcr :ensure t) ; Dependency of dante
(use package dante
  :ensure t
  ; Other options...
  )
```

**Comment by jyp** [comment]
Gah! I forgot the dependency in dante T_T.
