### ISSUE TITLE
Function xref-find-defintions doesn't work in test directories

### ISSUE THREAD

**Issue by tmcgilchrist** [jyp/dante#72]
Function xref-find-definitions doesn't work in `test` directories but it works correctly in `src`.

My basic project layout is:
```shell
$ tree -d -L 1
.
├── bin
├── dist
├── docs
├── src
├── test
└── tmp
```

Simplified cabal file of:
```
name: huck
...

library
  hs-source-dirs: src
...

test-suite test
  hs-source-dirs: test

```

I get an error of `user-error: No definitions found for: "/var/folders/zn/dp80b1h55bb_dpqmdyld59hm0000gn/T/dante63543Xt3.hs" 105 30 105 38 Position`

Is this a dante issue or something related to xref proper?

**Comment by jyp** [comment]
Perhaps you need to configure `dante-target` for your tests?

xref does nothing special depending on the source directory, nor does dante. As far as I can see only the cabal target can have an influence.

**Comment by jyp** [comment]
Closing in absence of information
