### ISSUE TITLE
Running cabal repl when already in a nix shell

### ISSUE THREAD

**Issue by SFrijters** [jyp/dante#76]
I use a `shell.nix` that also includes some haskell tools such as hlint/stylish-haskell and I would like to start my emacs from that shell so that they are on the path.
However, when dante starts it invokes nix-shell again and I get

```
nix/store/gqg2vrcq7krqi9rrl6pphvsg81sb8pjw-gcc-wrapper-7.3.0/nix-support/utils.sh: line 68: /nix/store/1sq8mqjly01pb1nf471phgbgc71v12yy-expand-response-params/bin/expand-response-params: Argument list too long
/nix/store/gqg2vrcq7krqi9rrl6pphvsg81sb8pjw-gcc-wrapper-7.3.0/bin/cc: line 183: /nix/store/bm7pb1s7rx1ad80706b5xqrznq7fgpgx-gcc-7.3.0/bin/gcc: Argument list too long
`cc' failed in phase `C Compiler'. (Exit code: 126)
```

Would it be possible to have dante use Nix's IN_NIX_SHELL environment variable to check if a new shell needs to be spawned or if `cabal repl` can be called directly?

**Comment by jyp** [comment]
I am not sure that this should be made the default. You should customize `dante-repl-command-line-methods-alist` or simply set `dante-repl-command-line` to what you want.
