### ISSUE TITLE
Error about void lcr-scheduler

### ISSUE THREAD

**Issue by seanparsons** [jyp/dante#77]
Whenever I start dante I get the following error:

```
error in process filter: Symbol's definition is void: lcr-scheduler
```

Only main difference that I can think of is that I'm using the `emacsWithPackages` Nix functionality to get the packages installed, so I'm not using `use-package`. I tried adding `lcr` as a direct dependency and it didn't make any difference.

**Comment by acarrico** [comment]
I have the same trouble. It looks like commit 68bfb9259ab7ad916739e2f5e3720eb3ceb7004a says `lcr` 1.0 is required. I've got 0.9 and 20180224.1243, but I'm don't know how to change `emacsWithPackages` to get 1.0.

**Comment by seanparsons** [comment]
Fixed this by using `melpaStablePackages` instead of `melpaPackages`.
