### ISSUE TITLE
autofix non-exhaustive pattern matches.

### ISSUE THREAD

**Issue by tmcgilchrist** [jyp/dante#8]
I'm utterly failing at customising the `dante-auto-fix` regex to add support for this error

```
[-Wincomplete-patterns]
    Pattern match(es) are non-exhaustive
    In a case alternative: Patterns not matched: (Blah _)
```

any tips for how the regex works in dante would be appreciated.

**Comment by jyp** [comment]
Please check the linked commit. It's not perfect but it'll work for a case expression which is formatted in the usual way.
