### ISSUE TITLE
Option to use nix-shell --pure

### ISSUE THREAD

**Issue by siddharthist** [jyp/dante#82]
One of the great advantages of using Nix is build isolation. When passing the `--pure` flag to `nix-shell`, you can be (reasonably) certain that your build doesn't use anything not declared in your Nix file. While one can customize `dante-repl-command-line` and `dante-repl-command-line-methods-alist`, it would be great to have a simple `booleanp` flag which a user could toggle when they want to use `--pure`.

**Comment by jyp** [comment]
There are just too many different ways to start GHCi (heck, you could even use a GHCi fork), so I don't really feel like adding a flag for this. 

However, the sane default is `--pure`, so I have activated that in 475299d

**Comment by siddharthist** [comment]
@jyp Great, thanks!

**Comment by patrl** [comment]
Just wanted to chip in to mention that setting `--pure` as the default breaks what I imagine to be a fairly common workflow -- using `cabal` as a built tool with nix-integration enabled, and using `cabal2nix` to generate a `shell.nix` file. The nix-shell that dante drops into doesn't have `cabal` on its path, and dante errors out.

**Comment by jyp** [comment]
@patrl  Right. I've added an `impure-nix` method which can be activated by customizing `dante-repl-command-line-methods`

**Comment by patrl** [comment]
Ah, thanks so much! This helps a lot.
