### ISSUE TITLE
dante-async-load-current-buffer causes save-hooks to run

### ISSUE THREAD

**Issue by jmcarthur** [jyp/dante#84]
This function calls save-buffer, which causes the whitespace cleanup in my before-save-hook to run. This makes coding difficult, because if I put a space at the end of a line or hit enter at the end of the buffer, it is immediately undone.

**Comment by jyp** [comment]
What about triggering flycheck/flymake only upon save?

```
(setq flymake-no-changes-timeout nil)
    (setq flymake-start-syntax-check-on-newline nil)
    (setq 'flycheck-check-syntax-automatically '(save mode-enabled))
```

**Comment by jmcarthur** [comment]
That's an option, of course.

I don't know how it works, but it seems that for the other languages I use flycheck with I get on-the-fly checking without it actually having to save. I'm guessing there's some build system related reason dante works this way?

**Comment by jyp** [comment]
GHCi can get confused when using temporary files. Basically using temporary files is a moving part which IMO creates more complications than what it solves.
