### ISSUE TITLE
Dante's autosave does not respect before-save-hook

### ISSUE THREAD

**Issue by endgame** [jyp/dante#86]
I have `'whitespace-cleanup` in my `before-save-hook`. Dante's autosave does not run this hook when a check is triggered.

I suspect that this is by design, because if you have more aggressive reformatters in `before-save-hook`, dante would make everything jump around while you're trying to work.

Is there a hook that runs specifically before dante's autosave?

**Comment by endgame** [comment]
Similarly, it drops backup files all through my directories, despite my usual config arranging for them to be placed elsewhere.

I see that `dante.el` calls `basic-save-buffer-1` to avoid running hooks. Perhaps an advice or some other trickery to sub in (new) `dante-before-save-hook` and `dante-after-save-hook` would get us the best of both worlds?

If this sounds like a good plan, I'll have a crack at writing it.

**Comment by endgame** [comment]
So it seems that Dante has recently started using a temporary file or something on my machine, which means this isn't bothering me so much any more (as I manually save, which runs the hooks). Is that correct?

**Comment by jyp** [comment]
I don't think that I have changed the general strategy. However you've probably configured to run flycheck on save only, which does what you want. All in all, I think that this is the safest thing to do.

**Comment by endgame** [comment]
Interesting. Something has changed in my config, because I'm getting flycheck errors relating to files with names like `/tmp/danteXXXXXX.hs` instead of my main buffer autosaving all the time and dropping backup files in the way. Perhaps the underlying flycheck code changed?

In any case, this doesn't seem to matter any more.

**Comment by endgame** [comment]
And something has changed back in my config somewhere. I will have to fiddle with this some more.

**Comment by jyp** [comment]
Should be fixed by c7d7070
