### ISSUE TITLE
Feature request: ability to enable `dante-mode` only on certain projects

### ISSUE THREAD

**Issue by ckoparkar** [jyp/dante#88]
As someone who (recently) switched to `dante` from `intero`, I wish I could have something similar to `intero`'s [whitelists/blacklists](https://github.com/commercialhaskell/intero#whitelistingblacklisting-projects) -- which allows one to enable `intero-mode` only for specific packages. Otherwise it stays out of the way.

Is there a way to do something similar with `dante` (I looked and couldn't find any relevant `defcustom`) ? I could certainly use some custom configuration to achieve this goal, but do you think it could be useful to add this ability to `dante` ?

@jyp  Perhaps you already considered this, and decided against it. If so, could you tell us why ? On the other hand, if you think this could be useful, I would be happy to give it a shot.

**Comment by jyp** [comment]
@ckoparkar 
There is no "global-dante-mode": dante never activates itself on its own. One has to explicitly call `dante-mode` to activate it. So it should be easy to add a condition around your call to `dante-mode`. I think I'd like to use a directory-local variable for that, say `ckoparkar-no-dante-here`. Then it becomes simply:

```
(unless (bound-and-true-p 'ckoparkar-no-dante-here)
  (dante-mode))
```

I had not considered this before. But, I am trying to keep dante as lean as possible and I do not think that such a mechanism belongs to dante itself.

**Comment by ckoparkar** [comment]
> There is no "global-dante-mode": dante never activates itself on its own. One has to explicitly call dante-mode to activate it. 
 
That's correct. Although merely using `(add-hook 'haskell-mode-hook 'dante-mode)` would activate it on every Haskell file. 

> So it should be easy to add a condition around your call to dante-mode. I think I'd like to use a directory-local variable for that ...

Thanks! I'll use something like this.

>  I am trying to keep dante as lean as possible and I do not think that such a mechanism belongs to dante itself.

Fair enough. I'll go ahead and close this :)
