### ISSUE TITLE
Dante cannot discover test-suite deps

### ISSUE THREAD

**Issue by tsoernes** [jyp/dante#89]
I have a binary and test suite in the cabal file. Dante works fine with the binary project, but `haskell-dante` is unable to import files from the local test directory even though `stack test` runs fine and does not complain about imports (nor missing modules or anything).

**Comment by tsoernes** [comment]
![screenshot_20181006_115734](https://user-images.githubusercontent.com/6782404/46570071-0a7f6f80-c95f-11e8-9b6e-34c2b07449fc.png)
Have tried restarting both dante and emacs.

**Comment by themoritz** [comment]
I can solve this issue by placing a `.dir-locals.el` file with the line `((haskell-mode . ((dante-target . "tests"))))` (or whatever your test suite is called in the cabal file) in the directory that contains the test source files.

**Comment by haitlahcen** [comment]
As @themoritz said, you have to specify the `target` in each directory, in the `src` (library), `test` (test suite) and `app` (cli or w/e) directories and so on...

**Comment by tsoernes** [comment]
Perhaps we could automated that based on the path of the current buffer
file? If "test" in project path then set Dante target to test.. Or would
that conflict with the folder structures that people are using.

Den tir. 30. okt. 2018 kl. 15:54 skrev Hussein Ait -Lahcen <
notifications@github.com>:

**Comment by haitlahcen** [comment]
The only way you could be sure of the target is by reading the .cabal file and find a target that contains the buffer's directory. `test`, `src` etc... are just named like that by default.

**Comment by freckletonj** [comment]
Related to: https://github.com/jyp/dante/issues/83

In `intero`, i used to be able to have multiple targets at once, allowing me to switch between `src/` files and `tests/` files, and have full support.

Based on the comment above, it sounds like a `.dir-locals.el` file should be all I need.


**EDIT:**

it looks like dante takes your `dante-target` and runs the command as `stack repl <target>`.

So the following _looks_ like it works so far:

```lisp
((haskell-mode . ((dante-target . "--test"))))
```

which runs the command `stack repl --test`. (and remember `stack repl` is a synonym for `stack ghci`)
