### ISSUE TITLE
dante not using dante-repl-command-line in spacemacs

### ISSUE THREAD

**Issue by shmish111** [jyp/dante#95]
I am trying to get dante working with bazel in spacemacs, I have the following config:

In layers:

```
     (haskell :variables
              haskell-completion-backend 'dante
              haskell-process-log t
              ;; dante-project-root "/Users/davidsmith/tweag/plutus-bazel"
              ;; dante-repl-command-line '("/nix/store/yziylmm7zinsgx7xd6fwf1ma0jczhjgi-bazel-0.17.1/bin/bazel" "run" "//language-plutus-core:language-plutus-core-repl")
              )
```

In user config

```
    (use-package dante
      :ensure t
      :after haskell-mode
      :commands 'dante-mode
      :init
      (setq dante-repl-command-line  '("/nix/store/yziylmm7zinsgx7xd6fwf1ma0jczhjgi-bazel-0.17.1/bin/bazel" "run" "//thetarget"))
      ;; (setq dante-project-root "/Users/davidsmith/theprojectroot")
      (add-hook 'haskell-mode-hook 'dante-mode)
      )
```

However dante reports `Dante: Starting GHCi: cabal new-repl --builddir=dist/dante`, it doesn't appear to pick up that I set `dante-repl-command-line`.

**Comment by jyp** [comment]
Did you try M-x describe-variable dante-repl-command-line in your buffer before starting dante? (Use dante-restart if necessary).

BTW: if you want to add bazel support, you should add rather add a method in dante-repl-command-line-methods-alist

**Comment by rihardsk** [comment]
It seems i have the same problem. @jyp heres what `M-x describe-variable dante-repl-command-line` gives me:
```
dante-repl-command-line is a variable defined in ‘dante.el’.
Its value is
("nix-shell" "--pure" "--run"
 (concat "cabal repl "
         (or dante-target "")
         " --builddir=dist/dante"))
Original value was nil
Local in buffer Main.hs; global value is 
("nix-shell" "--run" "cabal new-configure && cabal new-repl --ghc-option -fobject-code --builddir=dist/dante")
```
The "global" value is the thing i've set in my `.dir-locals.el`. But somehow it get's ignored and the "local" value get's set and used instead.

Just in case - here's my `.dir-locals.el`
```elisp
((haskell-mode
  . ((dante-repl-command-line
      . ("nix-shell" "--run" "cabal new-configure && cabal new-repl --ghc-option -fobject-code --builddir=dist/dante"
         )
      ))
  ))
```

I'm using `dante` as part of the `haskell` layer in `spacemacs`. I've looked through the layer's files and couldn't find anything touching the `dante-repl-command-line` variable.

**Comment by emilypi** [comment]
I'm getting the same thing as @rihardsk. Dante actually seems to now be completely ignoring the `dante-repl-command-line` value set by my `.dir-locals.el`, though, it does pick up the local change in the current buffer. This seems to be a recent regression, since a few updates ago, this was working fine.

![image](https://user-images.githubusercontent.com/10459342/52526064-56318500-2c81-11e9-89bf-8e9a228c430a.png)

**Comment by jyp** [comment]
I see what I did wrong. However, I'd like to switch to using  `dante-methods` and `dante-methods-alist` as customisation method, which is more flexible. Could you give it a try?

**Comment by emilypi** [comment]
Sure, I can use the `dante-methods-alist`. But i do have some feedback. I understand _why_ you'd like to keep with the `alist` approach, but it would be a problem as-is if it were the only way to handle repl commands. Take the `nix` commands, for example:

```lisp
 (new-nix dante-cabal-new-nix ("nix-shell" "--pure" "--run" (concat "cabal new-repl " (or dante-target "") " --builddir=dist/dante")))
```

This will be run if `cabal.project`, `shell.nix` and `default.nix` are present. However, not all nix-builds are standardized in a way that means those file handles are significant. For instance, if that runs on a nix project which _doesn't expose cabal as a shell in `shell.nix`_, but still has cabal support for people use either cabal or nix exclusively, then it will fail every time I try and start up that project. Here is a [concrete example](https://github.com/qfpl/waargonaut/) of a project which doesn't expose cabal in its `shell.nix` for which i have to have a custom command running. 

The solution in this case is to not run the nix commands using `--pure`, which may anger some nix users (but hey, you get to use the `v2-*` command set!). Nix is complicated and there are no best practices yet unfortunately 😦 


That said, having `dante` work with `dir-locals` should still be a fallback option for people like above, who are doing 1-off things like configuration.

**Comment by jyp** [comment]
Alright, I'll try and keep this configuration route open.
