### ISSUE TITLE
support `cabal.project` in parent directories

### ISSUE THREAD

**Issue by sboosali** [jyp/dante#96]
"megarepos" (such as `servant`) are a common pattern for haskell project management, previously only suppported conveniently by `stack`. with `cabal-install-2.0+`, project files like this:

    packages:
      ./example
      ./example-types

are now becoming ubiquitous. `dante` currently ignores `cabal.project` files, which causes issues for most of the packages I develop. my workaround is adding `.dir-locals.el` in every project I contribute to, like:

    ((haskell-mode
      . ((dante-project-root . "~/haskell/skeletor/"))))

which decreases its relocatability.

I suggest adding a `dante-force-cabal-project` option that `(dante-project-root)` respects.

**Comment by sboosali** [comment]
something like this: 

https://github.com/jyp/dante/compare/master...sboosali:cabal-project

(currently unteseted)

**Comment by jyp** [comment]
I do believe that this is now fixed in master.
