### ISSUE TITLE
Feature Request: Log the repl startup process

### ISSUE THREAD

**Issue by emilypi** [jyp/dante#99]
Hi All

Is there any way to log the repl startup process when `dante-mode` starts? It would be a great help to know how long it will take until `dante` kicks in so I'm not sitting in limbo until i see `dante:loaded` in the minibuffer. Larger haskell projects may take a good 10min to start up a repl, especially if there's nix stuff to build, and it would be a great help to know that it _is_ building, as well what went wrong right there in the buffer. Is there any way to simply enable this feature if it exists?

**Comment by jyp** [comment]
Where would you prefer to see this information?

**Comment by emilypi** [comment]
perhaps in the `*dante:<project>:<target>*` buffer, so that we can see when and where things fail in the build along with the stuff dante spits out. Or, it could be added as an option to pipe the output to a separate buffer if you'd like to keep that space clean. I'm open to suggestions from people.

**Comment by emilypi** [comment]
That solved it! Thank you. That helps me sell this to the team much more easily.

**Comment by jyp** [comment]
Great! If you have an idea to report GHCi loading in a simple non-obtrusive way, let me know. I'm closing in the meantime.
